# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ApplicantResData(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, applicant: str=None, num: int=None):  # noqa: E501
        """ApplicantResData - a model defined in Swagger

        :param applicant: The applicant of this ApplicantResData.  # noqa: E501
        :type applicant: str
        :param num: The num of this ApplicantResData.  # noqa: E501
        :type num: int
        """
        self.swagger_types = {
            'applicant': str,
            'num': int
        }

        self.attribute_map = {
            'applicant': 'applicant',
            'num': 'num'
        }
        self._applicant = applicant
        self._num = num

    @classmethod
    def from_dict(cls, dikt) -> 'ApplicantResData':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ApplicantRes_data of this ApplicantResData.  # noqa: E501
        :rtype: ApplicantResData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def applicant(self) -> str:
        """Gets the applicant of this ApplicantResData.


        :return: The applicant of this ApplicantResData.
        :rtype: str
        """
        return self._applicant

    @applicant.setter
    def applicant(self, applicant: str):
        """Sets the applicant of this ApplicantResData.


        :param applicant: The applicant of this ApplicantResData.
        :type applicant: str
        """

        self._applicant = applicant

    @property
    def num(self) -> int:
        """Gets the num of this ApplicantResData.


        :return: The num of this ApplicantResData.
        :rtype: int
        """
        return self._num

    @num.setter
    def num(self, num: int):
        """Sets the num of this ApplicantResData.


        :param num: The num of this ApplicantResData.
        :type num: int
        """

        self._num = num
