# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class AreaResData(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, year: str=None, area: str=None, num: int=None):  # noqa: E501
        """AreaResData - a model defined in Swagger

        :param year: The year of this AreaResData.  # noqa: E501
        :type year: str
        :param area: The area of this AreaResData.  # noqa: E501
        :type area: str
        :param num: The num of this AreaResData.  # noqa: E501
        :type num: int
        """
        self.swagger_types = {
            'year': str,
            'area': str,
            'num': int
        }

        self.attribute_map = {
            'year': 'year',
            'area': 'area',
            'num': 'num'
        }
        self._year = year
        self._area = area
        self._num = num

    @classmethod
    def from_dict(cls, dikt) -> 'AreaResData':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AreaRes_data of this AreaResData.  # noqa: E501
        :rtype: AreaResData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def year(self) -> str:
        """Gets the year of this AreaResData.


        :return: The year of this AreaResData.
        :rtype: str
        """
        return self._year

    @year.setter
    def year(self, year: str):
        """Sets the year of this AreaResData.


        :param year: The year of this AreaResData.
        :type year: str
        """

        self._year = year

    @property
    def area(self) -> str:
        """Gets the area of this AreaResData.


        :return: The area of this AreaResData.
        :rtype: str
        """
        return self._area

    @area.setter
    def area(self, area: str):
        """Sets the area of this AreaResData.


        :param area: The area of this AreaResData.
        :type area: str
        """

        self._area = area

    @property
    def num(self) -> int:
        """Gets the num of this AreaResData.


        :return: The num of this AreaResData.
        :rtype: int
        """
        return self._num

    @num.setter
    def num(self, num: int):
        """Sets the num of this AreaResData.


        :param num: The num of this AreaResData.
        :type num: int
        """

        self._num = num
