# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.area_res_areas_data import AreaResAreasData  # noqa: F401,E501
from swagger_server import util


class AreaResAreas(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, area: str=None, data: AreaResAreasData=None):  # noqa: E501
        """AreaResAreas - a model defined in Swagger

        :param area: The area of this AreaResAreas.  # noqa: E501
        :type area: str
        :param data: The data of this AreaResAreas.  # noqa: E501
        :type data: AreaResAreasData
        """
        self.swagger_types = {
            'area': str,
            'data': AreaResAreasData
        }

        self.attribute_map = {
            'area': 'area',
            'data': 'data'
        }
        self._area = area
        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'AreaResAreas':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AreaRes_areas of this AreaResAreas.  # noqa: E501
        :rtype: AreaResAreas
        """
        return util.deserialize_model(dikt, cls)

    @property
    def area(self) -> str:
        """Gets the area of this AreaResAreas.


        :return: The area of this AreaResAreas.
        :rtype: str
        """
        return self._area

    @area.setter
    def area(self, area: str):
        """Sets the area of this AreaResAreas.


        :param area: The area of this AreaResAreas.
        :type area: str
        """

        self._area = area

    @property
    def data(self) -> AreaResAreasData:
        """Gets the data of this AreaResAreas.


        :return: The data of this AreaResAreas.
        :rtype: AreaResAreasData
        """
        return self._data

    @data.setter
    def data(self, data: AreaResAreasData):
        """Sets the data of this AreaResAreas.


        :param data: The data of this AreaResAreas.
        :type data: AreaResAreasData
        """

        self._data = data
