# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class AreaResAreasData(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, num: int=None):  # noqa: E501
        """AreaResAreasData - a model defined in Swagger

        :param num: The num of this AreaResAreasData.  # noqa: E501
        :type num: int
        """
        self.swagger_types = {
            'num': int
        }

        self.attribute_map = {
            'num': 'num'
        }
        self._num = num

    @classmethod
    def from_dict(cls, dikt) -> 'AreaResAreasData':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AreaRes_areas_data of this AreaResAreasData.  # noqa: E501
        :rtype: AreaResAreasData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def num(self) -> int:
        """Gets the num of this AreaResAreasData.


        :return: The num of this AreaResAreasData.
        :rtype: int
        """
        return self._num

    @num.setter
    def num(self, num: int):
        """Sets the num of this AreaResAreasData.


        :param num: The num of this AreaResAreasData.
        :type num: int
        """

        self._num = num
