# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.detail_res_data import DetailResData  # noqa: F401,E501
from swagger_server import util


class DetailRes(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, data: DetailResData=None):  # noqa: E501
        """DetailRes - a model defined in Swagger

        :param data: The data of this DetailRes.  # noqa: E501
        :type data: DetailResData
        """
        self.swagger_types = {
            'data': DetailResData
        }

        self.attribute_map = {
            'data': 'data'
        }
        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'DetailRes':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DetailRes of this DetailRes.  # noqa: E501
        :rtype: DetailRes
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self) -> DetailResData:
        """Gets the data of this DetailRes.


        :return: The data of this DetailRes.
        :rtype: DetailResData
        """
        return self._data

    @data.setter
    def data(self, data: DetailResData):
        """Sets the data of this DetailRes.


        :param data: The data of this DetailRes.
        :type data: DetailResData
        """

        self._data = data
