# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class PatentReportReq(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, user_id: str=None, key: str=None, industry: str=None, area: str=None, applicant: str=None):  # noqa: E501
        """PatentReportReq - a model defined in Swagger

        :param user_id: The user_id of this PatentReportReq.  # noqa: E501
        :type user_id: str
        :param key: The key of this PatentReportReq.  # noqa: E501
        :type key: str
        :param industry: The industry of this PatentReportReq.  # noqa: E501
        :type industry: str
        :param area: The area of this PatentReportReq.  # noqa: E501
        :type area: str
        :param applicant: The applicant of this PatentReportReq.  # noqa: E501
        :type applicant: str
        """
        self.swagger_types = {
            'user_id': str,
            'key': str,
            'industry': str,
            'area': str,
            'applicant': str
        }

        self.attribute_map = {
            'user_id': 'user_id',
            'key': 'key',
            'industry': 'industry',
            'area': 'area',
            'applicant': 'applicant'
        }
        self._user_id = user_id
        self._key = key
        self._industry = industry
        self._area = area
        self._applicant = applicant

    @classmethod
    def from_dict(cls, dikt) -> 'PatentReportReq':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PatentReportReq of this PatentReportReq.  # noqa: E501
        :rtype: PatentReportReq
        """
        return util.deserialize_model(dikt, cls)

    @property
    def user_id(self) -> str:
        """Gets the user_id of this PatentReportReq.


        :return: The user_id of this PatentReportReq.
        :rtype: str
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id: str):
        """Sets the user_id of this PatentReportReq.


        :param user_id: The user_id of this PatentReportReq.
        :type user_id: str
        """

        self._user_id = user_id

    @property
    def key(self) -> str:
        """Gets the key of this PatentReportReq.


        :return: The key of this PatentReportReq.
        :rtype: str
        """
        return self._key

    @key.setter
    def key(self, key: str):
        """Sets the key of this PatentReportReq.


        :param key: The key of this PatentReportReq.
        :type key: str
        """

        self._key = key

    @property
    def industry(self) -> str:
        """Gets the industry of this PatentReportReq.


        :return: The industry of this PatentReportReq.
        :rtype: str
        """
        return self._industry

    @industry.setter
    def industry(self, industry: str):
        """Sets the industry of this PatentReportReq.


        :param industry: The industry of this PatentReportReq.
        :type industry: str
        """

        self._industry = industry

    @property
    def area(self) -> str:
        """Gets the area of this PatentReportReq.


        :return: The area of this PatentReportReq.
        :rtype: str
        """
        return self._area

    @area.setter
    def area(self, area: str):
        """Sets the area of this PatentReportReq.


        :param area: The area of this PatentReportReq.
        :type area: str
        """

        self._area = area

    @property
    def applicant(self) -> str:
        """Gets the applicant of this PatentReportReq.


        :return: The applicant of this PatentReportReq.
        :rtype: str
        """
        return self._applicant

    @applicant.setter
    def applicant(self, applicant: str):
        """Sets the applicant of this PatentReportReq.


        :param applicant: The applicant of this PatentReportReq.
        :type applicant: str
        """

        self._applicant = applicant
