# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class TechnologyResData(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, _class: str=None, num: int=None):  # noqa: E501
        """TechnologyResData - a model defined in Swagger

        :param _class: The _class of this TechnologyResData.  # noqa: E501
        :type _class: str
        :param num: The num of this TechnologyResData.  # noqa: E501
        :type num: int
        """
        self.swagger_types = {
            '_class': str,
            'num': int
        }

        self.attribute_map = {
            '_class': 'class',
            'num': 'num'
        }
        self.__class = _class
        self._num = num

    @classmethod
    def from_dict(cls, dikt) -> 'TechnologyResData':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The TechnologyRes_data of this TechnologyResData.  # noqa: E501
        :rtype: TechnologyResData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def _class(self) -> str:
        """Gets the _class of this TechnologyResData.


        :return: The _class of this TechnologyResData.
        :rtype: str
        """
        return self.__class

    @_class.setter
    def _class(self, _class: str):
        """Sets the _class of this TechnologyResData.


        :param _class: The _class of this TechnologyResData.
        :type _class: str
        """

        self.__class = _class

    @property
    def num(self) -> int:
        """Gets the num of this TechnologyResData.


        :return: The num of this TechnologyResData.
        :rtype: int
        """
        return self._num

    @num.setter
    def num(self, num: int):
        """Sets the num of this TechnologyResData.


        :param num: The num of this TechnologyResData.
        :type num: int
        """

        self._num = num
