# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Trend1ResData(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, year: str=None, num: int=None):  # noqa: E501
        """Trend1ResData - a model defined in Swagger

        :param year: The year of this Trend1ResData.  # noqa: E501
        :type year: str
        :param num: The num of this Trend1ResData.  # noqa: E501
        :type num: int
        """
        self.swagger_types = {
            'year': str,
            'num': int
        }

        self.attribute_map = {
            'year': 'year',
            'num': 'num'
        }
        self._year = year
        self._num = num

    @classmethod
    def from_dict(cls, dikt) -> 'Trend1ResData':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Trend1Res_data of this Trend1ResData.  # noqa: E501
        :rtype: Trend1ResData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def year(self) -> str:
        """Gets the year of this Trend1ResData.


        :return: The year of this Trend1ResData.
        :rtype: str
        """
        return self._year

    @year.setter
    def year(self, year: str):
        """Sets the year of this Trend1ResData.


        :param year: The year of this Trend1ResData.
        :type year: str
        """

        self._year = year

    @property
    def num(self) -> int:
        """Gets the num of this Trend1ResData.


        :return: The num of this Trend1ResData.
        :rtype: int
        """
        return self._num

    @num.setter
    def num(self, num: int):
        """Sets the num of this Trend1ResData.


        :param num: The num of this Trend1ResData.
        :type num: int
        """

        self._num = num
