# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class TypeResData(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, type: str=None, num: int=None):  # noqa: E501
        """TypeResData - a model defined in Swagger

        :param type: The type of this TypeResData.  # noqa: E501
        :type type: str
        :param num: The num of this TypeResData.  # noqa: E501
        :type num: int
        """
        self.swagger_types = {
            'type': str,
            'num': int
        }

        self.attribute_map = {
            'type': 'type',
            'num': 'num'
        }
        self._type = type
        self._num = num

    @classmethod
    def from_dict(cls, dikt) -> 'TypeResData':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The TypeRes_data of this TypeResData.  # noqa: E501
        :rtype: TypeResData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def type(self) -> str:
        """Gets the type of this TypeResData.


        :return: The type of this TypeResData.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type: str):
        """Sets the type of this TypeResData.


        :param type: The type of this TypeResData.
        :type type: str
        """

        self._type = type

    @property
    def num(self) -> int:
        """Gets the num of this TypeResData.


        :return: The num of this TypeResData.
        :rtype: int
        """
        return self._num

    @num.setter
    def num(self, num: int):
        """Sets the num of this TypeResData.


        :param num: The num of this TypeResData.
        :type num: int
        """

        self._num = num
